matrix:
  url: 'http://localhost:8888'
  as_token: 'as_token'
  hs_token: 'hs_token'
  master_user_id: '@_xmpp_master:localhost'
  prefix: '_xmpp_'
  homeserver: 'https://localhost:8448'
  disable_ssl_validation: true
  #ssl:
  #  type: pkcs12
  #  key_store: ~/keystore.pkcs12
  #  key_store_password: 123

module:
  xmpp:
    domain: 'xmpp-server'
    port: 5269
    ssl:
      type: pkcs12
      key_store: /home/saimaa/cert_xmpp/xmpps.pkcs12
      key_store_password: xmpp
      disable_ssl_validation: true
    #ssl:
    #  type: pem
    #  key: ~/privkey.pem
    #  chain: ~/chain.pem

  activitypub:
    domain: 'ap-server'
    port: 80
    ssl:
      type: pem
      key: /home/saimaa/cert_ap/key.pem
      chain: /home/saimaa/cert_ap/chain.pem

database:
  username: saimaa
  password: saimaa
  url: jdbc:postgresql://localhost/saimaa
  properties:
    charSet: UTF-8
